services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models
      - ./data:/app/data
    environment:
      - DOCKER_ENV=1
    restart: unless-stopped

  dashboard:
    build: ./dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./models:/models
      - ./data:/app/data
    depends_on:
      - api
    restart: unless-stopped
